#<!-- controllers-->


xingtian:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 

  # Position Controllers ---------------------------------------
  /gazebo_ros_control
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: zqt_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint2_effort_controller:
    type: effort_controllers/JointPositionController
    joint: zqt_joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint3_velocity_controller:
    type: velocity_controllers/JointPositionController
    joint: zqt_joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}